### ISSUE TITLE
Feature Request: skipOnFirstFailedRule 

### ISSUE THREAD

**Issue by vinoct6** [benas/easy-rules#10]
Like we already have skipOnFirstAppliedRule, It would be nice to have an option  skipOnFirstFailedRule .
For now, if there are three rules A, B and C, and if we need A, B and C to pass to evaluate a condition, then we can stop B and C being evaluated if  A fails. 

We can achieve this right now, using skipOnFirstAppliedRule, but it doesn't feel elegant and natural. Having skipOnFirstFailedRule  would be nice.

**Comment by benas** [comment]
Great idea! Thanks for the suggestion.

I'll plan that for next release. Keep tuned :-)

Regards

**Comment by benas** [comment]
Hi,

I have released version 2.0.0 with support for the "skipOnFirstFailedRule" parameter.

Do not hesitate to try it out :-)

Regards
Mahmoud
