### ISSUE TITLE
Android and EasyRules

### ISSUE THREAD

**Issue by mrinalKhanvilkar** [benas/easy-rules#14]
Since JMX is not supported in android, the dynamic configuration will not work. Do you have any plans for having a different way for dynamic configuration?

**Comment by benas** [comment]
Hi,

Unfortunately not :-( As far as I'm concerned, there is no JMX alternative that is android compatible.
Do you know such a solution?

The dynamic configuration feature is not usable in android (as discussed in issue #6).

Regards
Mahmoud
