### ISSUE TITLE
I want to use it in spring mvc

### ISSUE THREAD

**Issue by dylanliang** [benas/easy-rules#16]
how to use it ?  can u give me a example?

**Comment by benas** [comment]
Hi,

Easy Rules can be embedded in a web application indeed, it's a lightweight library.

We can imagine a rule that filters requests that come from a range of suspicious IPs:

```java
@Rule (name = "IpFilteringRule", description="Filter users with suspicious IPs" )
public class IpFilteringRule {

	private HttpServletRequest request;

	private boolean shouldBeFiltered;
    
	public IpFilteringRule(HttpServletRequest request) {
		this.request = request;
	}
	
    @Condition
    public boolean whenRequestIsSuspicious() {
        return request.getRemoteAddr().contains("10.26.65.98"); // change this to a configurable range of IPs
    }
	
    @Action
    public void thenFilterRequest() {
        shouldBeFiltered = true;
    }
	
	public boolean shouldBeFiltered() {
		return shouldBeFiltered;
	}
}
```

You can then register an instance of this rule in your spring mvc controller:

```java
@Controller
public class IndexController {

	private @Autowired HttpServletRequest request;
	
	private RulesEngine rulesEngine = aNewRulesEngine().build();
	
    @RequestMapping(value = {"/index", "/"})
    public String goToHomePage() {

		IpFilteringRule ipFilteringRule = new IpFilteringRule(request)
		rulesEngine.registerRule(ipFilteringRule);
		rulesEngine.fireRules();
		
		if (ipFilteringRule.shouldBeFiltered()) {
			return "error";
		} else {
			return "index";
		}
        
    }

}
```

The `IpFilteringRule` could be declared as a request-scoped spring bean in which you inject the current `HttpServletRequest`.

Of course, this requirement should be implemented using a servlet filter or a security framework, but I just used it to give you an example. Another scenario would be to create a rule to redirect users to a maintenance page if the current time is in a given slot.

Hope it help :-)
Regards
Mahmoud

**Comment by oliv37** [comment]
As RulesEngine  is not thread safe, you cannot use `private @Autowired RulesEngine rulesEngine;` it will provide only one fresh instance for the IndexController **Singleton**. 
So you need to create a new instance inside the `goToHomePage` method, because if two requests reach this method at the same time you will have concurrency problem with the rules engine. 
As a result, I don't really see the benefits of using Easy Rules Spring...

**Comment by benas** [comment]
You are right, in this context,  the scope of rules AND the engine should be both "request" and not prototype. BTW, in the upcoming v3, the engine will be made stateless (hence thread safe) and the API will change into something like: `rulesEngine.fire(rules)`. So the previous example will be correct with v3.

**Comment by benas** [comment]
Hi @dylanleung @oliv37 

Starting from v3, the rules engine is thread safe. 
There is a [tutorial](https://github.com/j-easy/easy-rules/wiki/web-app) about how to use it in a webapp. 

Hope it helps.

NB: Spring support has been deprecated (details [here](https://github.com/j-easy/easy-rules/issues/74)), but Easy Rules can still be used with spring.

**Comment by oliv37** [comment]
Thanks, thread safety will be very helpfull when using use Easy Rules in a web context
