### ISSUE TITLE
How do i register rules once in a loop

### ISSUE THREAD

**Issue by ashishsoni** [benas/easy-rules#19]
I have stream of data coming but rules remains the same how can i register them once and use it on the data set why do i need to send the rule with the data every time.

**Comment by benas** [comment]
Hi,

This is somehow related to [this question](https://github.com/benas/easy-rules/issues/18): how to handle multiple data with the same rule definition?

Actually, once you have defined and registered your rule class, you can supply it with data to operate on using setters. 

Here is an example: [https://gist.github.com/benas/0eb38fc58b7364af1b74](https://gist.github.com/benas/0eb38fc58b7364af1b74) . It is a benchmark that was [asked](https://gitter.im/benas/easy-rules?at=5511cd4d610f433a6ab0cb4a) by another user, but it contains an example of your use case: you can see that `SimpleRule` is registered once and supplied with a set of data in a loop. Just modify the data and refire rules.

Hope it helps!
Kind regards
Mahmoud
