### ISSUE TITLE
problem with The method aNewRulesEngine() 

### ISSUE THREAD

**Issue by zougamohamed** [benas/easy-rules#20]
I'am just trying to execute the Hello World Example, I imported the Core Jar 2.1, annotations and everything else is fine but not this function, 
here is the error message in Eclipse :
The method aNewRulesEngine() is undefined for the type Launcher
and thank you in advance

**Comment by benas** [comment]
Hi,

I guess you missed the following static import:

[https://github.com/benas/easy-rules/blob/master/easyrules-samples/src/main/java/org/easyrules/samples/helloworld/Launcher.java#L31](https://github.com/benas/easy-rules/blob/master/easyrules-samples/src/main/java/org/easyrules/samples/helloworld/Launcher.java#L31)

This is a static factory method in the `RulesEngineBuilder` API.

You can create an engine using either:

`RulesEngine rulesEngine = RulesEngineBuilder.aNewRulesEngine().build();`

Or:

`RulesEngine rulesEngine = new RulesEngineBuilder().build();`

Do not hesitate to ask me if you need further support.

Regards
Mahmoud

**Comment by zougamohamed** [comment]
Eclipse was Updating The imports automatically, and every-time i was saving he was deleting that line for his own, Thank you so much for pointing that out, and specially thank you for you quick response, you saved me a lot of time :+1:

**Comment by benas** [comment]
You are welcome. Thank you for using Easy Rules!
