### ISSUE TITLE
Easy Rules logging issue

### ISSUE THREAD

**Issue by petergeorge73** [benas/easy-rules#21]
I am using easy rules extensively for my tomcat based web application . In my eclipse console I am seeing this logs . How do I disable these logs 

INFO: Rule 'FloodCertLinkPermissionRule' triggered.
Jul 29, 2015 4:38:34 PM org.easyrules.core.AnnotatedRulesEngine fireRules

**Comment by gs-spadmanabhan** [comment]
I think you should be able to use something like aNewRulesEngine().withSilentMode(true).build() to mute loggers.

**Comment by petergeorge73** [comment]
Thanks for the response . I am using AnnotatedRulesEngine , I dont see any method named withSilentMode . Are you refrerring to easyrules  java API ?

**Comment by gs-spadmanabhan** [comment]
Say for example, if you have an annotated rule,
```` java
    //Let's say this is your annotated rule
    private AnnotatedRule annotatedRule = new AnnotatedRule();
    //Create the rulesengine instance with silent mode option set to true in order to mute the loggers
    RulesEngine rulesEngine = RulesEngineBuilder.asNewRulesEngine().withSilentMode(true).build();
    //Now you need to register this annotated rule with the RulesEngine
    rulesEngine.registerRule(annotatedRule);
    rulesEngine.fireRules();
````
this should work for you.

**Comment by petergeorge73** [comment]
Thanks a lot . Fantastic

On Thu, Jul 30, 2015 at 11:58 PM, Sunand P <notifications@github.com> wrote:

> Say for example, if you have an annotated rule,
>
>     //Let's say this is your annotated rule
>     private AnnotatedRule annotatedRule = new AnnotatedRule();
>     //Create the rulesengine instance with silent mode option set to true in order to mute the loggers
>     RulesEngine rulesEngine = RulesEngineBuilder.asNewRulesEngine().withSilentMode(true).build();
>     //Now you need to register this annotated rule with the RulesEngine
>     rulesEngine.registerRule(annotatedRule);
>     rulesEngine.fireRules();
>
> this should work for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benas/easy-rules/issues/21#issuecomment-126560287>.
>



-- 
George Peter
Mobile +1561-479-8796
[The only thing constant in life is change]

**Comment by benas** [comment]
Hi @petergeorge73 ,

It looks like you are still using version 1.x. It strongly recommend you to use the last version 2.1.

Easy rules uses the Java util logging framework to have no dependencies. You can turn it off by setting the `OFF` [level](http://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html#OFF) or by using the `silent mode` parameter as suggested by @gs-spadmanabhan .

Thank you @gs-spadmanabhan for your reply!

Regards
Mahmoud

**Comment by petergeorge73** [comment]
Thanks a lot.

-----Original Message-----
