### ISSUE TITLE
Using @Rule in a meta annotation

### ISSUE THREAD

**Issue by cvsubs** [benas/easy-rules#25]
Thanks so much for the quick turn around on the rule name modification. 

Now annotating a rule class with just @Rule without a rule name automatically defaults the rule name to the class name, however, the rule class does not like a meta-annotation that has @Rule embedded in it. For example, I have defined my meta-annotation @BasicRule in the following manner. My tests throw an exception while parsing the class, complaining that it cannot find the @Rule annotation, even though I have annotated my rule class with @BasicRule. 

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Component
@Scope("prototype")
@Rule
public @interface BaseRule
{
 
}

Sample Stack Trace:
java.lang.IllegalArgumentException: Rule ‘XYZ' is not annotated with 'org.easyrules.annotation.Rule'
at org.easyrules.core.RuleDefinitionValidator.checkRuleClass(RuleDefinitionValidator.java:34)
at org.easyrules.core.RuleDefinitionValidator.validateRuleDefinition(RuleDefinitionValidator.java:26)
at org.easyrules.core.RuleProxy.asRule(RuleProxy.java:34)
at org.easyrules.core.DefaultRulesEngine.asRule(DefaultRulesEngine.java:209)
at org.easyrules.core.DefaultRulesEngine.registerRule(DefaultRulesEngine.java:101)

**Comment by richdouglasevans** [comment]
I've submitted a [pull request](https://github.com/benas/easy-rules/pull/26) to address your issue.

In the case where you've got lots of `Rules` that are also Spring-managed `@Components` that are also `prototype`-scoped, a custom `@Rule` annotation can reduce the amount of annotation boilerplate.

**Comment by benas** [comment]
@richdouglasevans, many thanks to you for adding support for meta-annotations!
I've merged your PR in the master branch.

@cvsubs Could you please give it a try with the last version of the master branch and keep us informed if this is ok in your use case? Sorry for not being able to push the snapshot version to maven central, I'm behind a nasty proxy :rage:

**Comment by benas** [comment]
@cvsubs I've got your email, glad to hear it works fine for you :smile:
kudos to @richdouglasevans for the great PR!

I've planned to release v2.2 by the end of this week. Keep tuned

Regards
Mahmoud
