### ISSUE TITLE
Move JMX support to a separate module so that the core engine can be used in Android

### ISSUE THREAD

**Issue by benas** [benas/easy-rules#4]
As discussed in issue #2 , Android does not support the JMX API. The core module of easy rules uses JMX by default which makes it unusable in an Android application.

The goal of this feature is to move JMX support to a separate module so that the core engine can be used both in Android and Java applications

**Comment by drem-darios** [comment]
I've opened a Pull Request for this issue. It can be found here: https://github.com/benas/easy-rules/pull/5
