### ISSUE TITLE
Question on skipping rules

### ISSUE THREAD

**Issue by vinoct6** [benas/easy-rules#9]
Hi,
   There is an option  skipOnFirstAppliedRule, through which, you can disable the subsequent rules, if one rule is executed. 
For example, if there are rules A, B and C, if rule A executes to true, then B and C won't be applied. Is my understanding correct ?

I am trying to achieve the below functionality, is there any way to do it ?

I have three rules A, B and C and it has to be executed like this

if(A && B && C) {//then do something}

This means that, if A fails, I should not execute B and C, since there is no point. Is there any way to do this thing ?

**Comment by benas** [comment]
Hi,

In fact, this is how the `skipOnFirstAppliedRule` works.

To implement your requirement, have you tried to use a [composite rule](http://www.easyrules.org/user-guide/defining-rules.html#composite-rules)?

you can create a composite rule from A, B, C and trigger it: If *all* conditions of A, B and C are satisfied, then actions will be executed.

Hope it helps,
Regards
Mahmoud

**Comment by vinoct6** [comment]
I looked at composite rule,.I am doing costly operations like database operations like in the @Condition. So I don't want rules B and C to execute in the first place if A returns false in the first place.

I guess ,skipOnFirstAppliedRule  this way :Given three rules A,B and C, if A returns true, then A's action will be executed and B and C won't be executed at all . Am I understanding it right ?

**Comment by benas** [comment]
You are right.

There is no better than a live example :-). Here it is:

```java
import org.easyrules.annotation.Action;
import org.easyrules.annotation.Condition;
import org.easyrules.annotation.Rule;
import org.easyrules.core.AnnotatedRulesEngine;

public class TestIssue9 {

    public static void main(String[] args) {

        A a = new A();
        B b = new B();
        C c = new C();

        AnnotatedRulesEngine rulesEngine = new AnnotatedRulesEngine(true);
        rulesEngine.registerRule(a);
        rulesEngine.registerRule(b);
        rulesEngine.registerRule(c);

        rulesEngine.fireRules();

    }

    @Rule(name = "A")
    public static class A {
        @Condition
        public boolean whenA() {
            System.out.println("checking A");
            return true;
        }
        @Action
        public void thenA() throws Exception {
            System.out.println("A executed");
        }
    }

    @Rule(name = "B")
    public static class B {
        @Condition
        public boolean whenB() {
            System.out.println("checking B");
            return true;
        }
        @Action
        public void thenB() throws Exception {
            System.out.println("B executed");
        }
    }

    @Rule(name = "C")
    public static class C {
        @Condition
        public boolean whenC() {
            System.out.println("checking C");
            return true;
        }
        @Action
        public void thenC() throws Exception {
            System.out.println("C executed");
        }
    }
}
```

If you run this example, you will get:

```
29-Apr-2015 14:38:40 org.easyrules.core.AbstractRulesEngine logEngineParameters
INFO: Skip on first applied rule: true
29-Apr-2015 14:38:40 org.easyrules.core.AbstractRulesEngine logEngineParameters
INFO: Rule priority threshold: 2,147,483,647
29-Apr-2015 14:38:40 org.easyrules.core.AnnotatedRulesEngine fireRules
INFO: Rule 'A' triggered.
checking A
A executed
29-Apr-2015 14:38:40 org.easyrules.core.AnnotatedRulesEngine fireRules
INFO: Rule 'A' performed successfully.
29-Apr-2015 14:38:40 org.easyrules.core.AnnotatedRulesEngine fireRules
INFO: Next rules will be skipped according to parameter skipOnFirstAppliedRule.
```

As you can see, when `skipOnFirstAppliedRule` is set to true (at engine construction time), A is executed but not B nor C.

**Comment by vinoct6** [comment]
Thank you very. One more question.
How do we collect the results of operations ?  For example, if all the rules run, I want to know if each rule was successful or not. Right now, what I am doing is, creating a mutable RuleResult object with boolean attributes like this

class RuleResult {
       boolean hasFirstRuleSucceded;
       boolean hasSecondtRuleSucceded;

}

and I pass the same RuleResult object to all the rules and set the corresponding boolean value in the @Action. Is there a better way to do this ?

**Comment by benas** [comment]
You can do it that way or simply add a flag in your rule that you can query after the rule has been executed:

```java
    @Rule(name = "my rule")
    public static class MyRule<T> {
        
        private boolean executed;
        
        private T result;
        
        //@Condition
        public boolean when() {
            return true;
        }
		
        //@Action
        public void then() throws MyException {
            try {
                System.out.println("C executed");
                result = null; // assign your result here
                executed = true;
            } catch (MyException e) {
                throw e;
            }
        }

        public boolean isExecuted() {
            return executed;
        }

        public T getResult() {
            return result;
        }
		
    }
```

After firing rules, you can query the rule and see if it has been executed and get the result.

**Comment by vinoct6** [comment]
Thank you
